spring.application.name=taskmanager-management

spring.datasource.url=jdbc:h2:file:~/.taskmanagger/data1/taskmanager_bd;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;CACHE_SIZE=131072;LOCK_MODE=0;WRITE_DELAY=10000
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
#logging.level.root=OFF
logging.level._org.springframework.web.servlet.HandlerMapping.Mappings: debug

# Disable limits
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1   

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.deserialization.accept-case-insensitive-enums=true
