spring.application.name=taskmanager

spring.application.version=2.0
server.port=8091
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/task
#spring.datasource.url=jdbc:h2:file:~/.taskmanagger/data1/taskmanager_bd;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;CACHE_SIZE=131072;LOCK_MODE=0;WRITE_DELAY=10000
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
#logging.level.root=OFF
logging.level._org.springframework.web.servlet.HandlerMapping.Mappings: debug
# CORS Configuration

# Disable limits
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1   

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  // Must be at least 48 characters long for HS384 (384 bits)
app.jwt.secret=mySecretKeyWithAtLeast48CharactersLong1234567890123!
# Default 1 day (24h)
app.jwt.expiration-ms=86400000


app.security.password.length-regex=.{8,}
app.security.password.uppercase-regex=.*[A-Z].*
app.security.password.lowercase-regex=.*[a-z].*
app.security.password.digit-regex=.*\\d.*
app.security.password.special-char-regex=.*[!@#$%^&*()_+\\-=\\[\\]{};':"\\\\|,.<>/?].*

app.cors.allowed-origins=*